In [256]:
import nltk

In [257]:
# nltk.download()

In [258]:
from nltk.corpus import brown

In [259]:
l=brown.categories()
l

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [260]:
s=brown.sents(categories="fiction")

In [261]:
# ' '.join(s[4])
print(s[:3])

[['Thirty-three'], ['Scotty', 'did', 'not', 'go', 'back', 'to', 'school', '.'], ['His', 'parents', 'talked', 'seriously', 'and', 'lengthily', 'to', 'their', 'own', 'doctor', 'and', 'to', 'a', 'specialist', 'at', 'the', 'University', 'Hospital', '--', 'Mr.', 'McKinley', 'was', 'entitled', 'to', 'a', 'discount', 'for', 'members', 'of', 'his', 'family', '--', 'and', 'it', 'was', 'decided', 'it', 'would', 'be', 'best', 'for', 'him', 'to', 'take', 'the', 'remainder', 'of', 'the', 'term', 'off', ',', 'spend', 'a', 'lot', 'of', 'time', 'in', 'bed', 'and', ',', 'for', 'the', 'rest', ',', 'do', 'pretty', 'much', 'as', 'he', 'chose', '--', 'provided', ',', 'of', 'course', ',', 'he', 'chose', 'to', 'do', 'nothing', 'too', 'exciting', 'or', 'too', 'debilitating', '.']]


In [262]:
## Tokenisation
# ' '.join(s[4])
# s[6]

In [263]:
f="""It was a very pleasent day. The weather was cool and there were light showers. I went to the market to buy some fruits."""

In [264]:
# document=""""""

In [265]:
# for i in s[3:7]:
#     document+=' '.join(i)

In [266]:
# document

In [267]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [268]:
sents=sent_tokenize(f)

In [269]:
sents

['It was a very pleasent day.',
 'The weather was cool and there were light showers.',
 'I went to the market to buy some fruits.']

In [270]:
len(sents)

3

In [271]:
sentence ="send all the 50 docs of 1,2,3 chapters to f43@gmail.com"

In [272]:
sentence.split()

['send',
 'all',
 'the',
 '50',
 'docs',
 'of',
 '1,2,3',
 'chapters',
 'to',
 'f43@gmail.com']

In [273]:
word_tokenize(sentence)

['send',
 'all',
 'the',
 '50',
 'docs',
 'of',
 '1,2,3',
 'chapters',
 'to',
 'f43',
 '@',
 'gmail.com']

In [274]:
##STOPWORDS

In [275]:
from nltk.corpus import stopwords

In [276]:
sw=set(stopwords.words('english'))

In [277]:
sw

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [278]:
def remove_sw(text,sw):
    useful=[w for w in text if w not in sw]
    return useful

In [279]:
print(remove_sw(sents[0].split(),sw))

['It', 'pleasent', 'day.']


In [280]:
## REGEX TOKENIZE

In [281]:
from nltk.tokenize import RegexpTokenizer

In [282]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')

In [90]:
useful_text=tokenizer.tokenize(sentence)

In [91]:
useful_text#HERE WE CAN SEE THAT NUMBERS ARE NOT THERE AND SPECIAL CHARS ARE ALSO NOT
#THERE BUT AS WE INCLUDED . AND @ EMAIL IS PRESERVED

['send', 'all', 'the', 'docs', 'of', 'chapters', 'to', 'f', '@gmail.com']

In [ ]:
##STEMMING and LEMMATIZATION

In [92]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [93]:
ps=PorterStemmer()

In [99]:
ps.stem('drinking')

'drink'

In [123]:
ss=SnowballStemmer('french')

In [124]:
ss.stem("")

''

In [128]:
from nltk.stem import WordNetLemmatizer as wl

In [129]:
wn=wl()

In [136]:
wn.lemmatize("")

'parlent'

In [138]:
##BUILDING A VOCAB

In [142]:
l

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [197]:
hr=(brown.sents(categories='reviews')[52:56])
hf=(brown.sents(categories='fiction')[52:56])
hn=(brown.sents(categories='news')[52:56])
hs=(brown.sents(categories='science_fiction')[52:56])

t=[hr,hf,hn,hs]

In [198]:
corpus=[]


In [199]:
for i in t:
    sr=""
    for j in i:
        sr+=(' '.join(j))
    corpus.append(sr)

In [200]:
(corpus)

["An exhibition of Evelyn Cibula's paintings will open with a reception Nov. 5 at the Evanston Community center , 828 Davis St. .It will continue all month .Abstractions and semi-abstractions by Everett McNear are being exhibited by the University Gallery of Notre Dame until Nov. 5 .In the line of operatic trades to cushion the budget , the Dallas Civic Opera will use San Francisco's new Leni Bauer-Ecsy production of `` Lucia Di Lammermoor '' this season , returning the favor next season when San Francisco uses the Dallas `` Don Giovanni '' , designed by Franco Zeffirelli .",
 "`` You don't eat enough , honey .Try to get that down '' .Rachel , observing , would say , `` He has to rediscover his own capacity .It'll take time '' .",
 "The Republicans must hold a primary under the county unit system -- a system which the party opposes in its platform .Sam Caldwell , State Highway Department public relations director , resigned Tuesday to work for Lt. Gov. Garland Byrd's campaign .Caldwell

In [201]:
from sklearn.feature_extraction.text import CountVectorizer

In [202]:
cv=CountVectorizer()

In [309]:
vc=cv.fit_transform(corpus)

In [308]:
vc#HERE WE SEE VOCAB IS 159 length 

array([[1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 3, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        2, 0, 4, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 3, 1,
        0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 

In [210]:
vc=vc.toarray()

In [212]:
vc[0]

array([1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 3, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       2, 0, 4, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 3, 1,
       0, 0, 0, 0, 1], dtype=int64)

In [215]:
cv.vocabulary_

{'an': 3,
 'exhibition': 43,
 'of': 90,
 'evelyn': 40,
 'cibula': 21,
 'paintings': 97,
 'will': 152,
 'open': 92,
 'with': 153,
 'reception': 106,
 'nov': 88,
 'at': 7,
 'the': 129,
 'evanston': 39,
 'community': 23,
 'center': 20,
 '828': 0,
 'davis': 29,
 'st': 121,
 'it': 66,
 'continue': 24,
 'all': 2,
 'month': 82,
 'abstractions': 1,
 'and': 4,
 'semi': 119,
 'by': 15,
 'everett': 41,
 'mcnear': 80,
 'are': 5,
 'being': 13,
 'exhibited': 42,
 'university': 143,
 'gallery': 50,
 'notre': 87,
 'dame': 28,
 'until': 144,
 'in': 65,
 'line': 74,
 'operatic': 94,
 'trades': 138,
 'to': 137,
 'cushion': 26,
 'budget': 14,
 'dallas': 27,
 'civic': 22,
 'opera': 93,
 'use': 146,
 'san': 116,
 'francisco': 47,
 'new': 85,
 'leni': 71,
 'bauer': 9,
 'ecsy': 37,
 'production': 103,
 'lucia': 78,
 'di': 32,
 'lammermoor': 68,
 'this': 133,
 'season': 118,
 'returning': 112,
 'favor': 45,
 'next': 86,
 'when': 149,
 'uses': 147,
 'don': 34,
 'giovanni': 53,
 'designed': 31,
 'franco': 48,
 '

In [216]:
#REVERSE MAPPING

In [219]:
numbers=vc[0]

In [224]:
n2s=cv.inverse_transform(vc[0])#THIS IS JUmbleD 

In [230]:
import numpy as np

In [235]:
n2s=np.array(n2s).tolist()

In [240]:
' '.join(n2s[0])

'828 abstractions all an and are at bauer being budget by center cibula civic community continue cushion dallas dame davis designed di don ecsy evanston evelyn everett exhibited exhibition favor francisco franco gallery giovanni in it lammermoor leni line lucia mcnear month new next notre nov of open opera operatic paintings production reception returning san season semi st the this to trades university until use uses when will with zeffirelli'

In [242]:
 #custom tokenizer to remove stopwords

In [252]:
def myTokenizer(document):
    words=tokenizer.tokenize(document.lower())
    words=remove_sw(words,sw)
    return words
    

In [255]:
print(' '.join(myTokenizer(document)))

teacher school principal conferred everyone agreed kept certain amount work home little danger losing term .scotty accepted decision indifference enter arguments .he discharged hospital two day checkup parents mr. mckinley described celebration lunch cafeteria campus .rachel wore smart hat warned recently smoking puffed cigarettes long ivory holder stained lipstick .


In [298]:
ncv=CountVectorizer(tokenizer=myTokenizer)

In [299]:
nvc=ncv.fit_transform(corpus)

In [300]:
# tokenizer.tokenize(corpus[0])

In [301]:
nvc=nvc.toarray()

In [305]:
len(nvc[0])#Here we notice that earlier the length of each f vector was 159. Now it's 120 by removing words

120

In [306]:
#bigrams and ngrams

In [325]:
bcv=CountVectorizer(ngram_range=(2,2))

In [326]:
bvc=bcv.fit_transform(corpus)

In [327]:
bvc=bvc.toarray()

In [330]:
bcv.vocabulary_

{'an exhibition': 5,
 'exhibition of': 54,
 'of evelyn': 109,
 'evelyn cibula': 51,
 'cibula paintings': 30,
 'paintings will': 120,
 'will open': 193,
 'open with': 115,
 'with reception': 195,
 'reception nov': 129,
 'nov at': 106,
 'at the': 11,
 'the evanston': 157,
 'evanston community': 50,
 'community center': 32,
 'center 828': 29,
 '828 davis': 0,
 'davis st': 39,
 'st it': 145,
 'it will': 84,
 'will continue': 192,
 'continue all': 33,
 'all month': 3,
 'month abstractions': 100,
 'abstractions and': 1,
 'and semi': 7,
 'semi abstractions': 143,
 'abstractions by': 2,
 'by everett': 20,
 'everett mcnear': 52,
 'mcnear are': 97,
 'are being': 8,
 'being exhibited': 18,
 'exhibited by': 53,
 'by the': 23,
 'the university': 165,
 'university gallery': 182,
 'gallery of': 63,
 'of notre': 112,
 'notre dame': 105,
 'dame until': 38,
 'until nov': 183,
 'nov in': 107,
 'in the': 81,
 'the line': 160,
 'line of': 92,
 'of operatic': 113,
 'operatic trades': 117,
 'trades to': 177,

In [331]:
ngramcv=CountVectorizer(ngram_range=(1,3))#all sentences will be in 1,2,3,4 clubs

In [332]:
sent1="This is good movie"
sent2="This was good movie"
sent3="This is not good movie"

In [333]:
corpus2=[sent1,sent2,sent3]

In [334]:
#TFIDF

In [339]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [340]:
tfidf=TfidfVectorizer()

In [343]:
tfvc=tfidf.fit_transform(corpus2).toarray()

In [344]:
tfvc#As we can see it gives importance of each word closer to 0 means not very useful and unique and opp for closer to 1

array([[0.46333427, 0.59662724, 0.46333427, 0.        , 0.46333427,
        0.        ],
       [0.41285857, 0.        , 0.41285857, 0.        , 0.41285857,
        0.69903033],
       [0.3645444 , 0.46941728, 0.3645444 , 0.61722732, 0.3645444 ,
        0.        ]])

In [345]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}